import { type ApiTableRow } from '@site/components/ApiTable';
export const rows: ApiTableRow[] = [
  {
    prop: 'type',
    desc: 'type of input',
    type: 'tag:text | password',
    required: 'false',
    default: 'text',
  },
  {
    prop: 'value',
    desc: 'value of input',
    type: 'string',
    required: 'false',
    default: '-',
  },
  {
    prop: 'placeholder',
    desc: 'placeholder of input',
    type: 'string',
    required: 'false',
    default: '-',
  },
  {
    prop: 'showCount',
    desc: 'whether show count of input',
    type: 'boolean',
    required: 'false',
    default: 'false',
  },
  {
    prop: 'showClear',
    desc: 'whether show clear button',
    type: 'boolean',
    required: false,
    default: 'false',
  },
  {
    prop: 'maxLength',
    desc: 'max length of input',
    type: 'number',
    required: 'false',
    default: '-',
  },
  {
    prop: 'prefix',
    desc: 'prefix node of input',
    type: 'React.ReactNode',
    required: 'false',
    default: '-',
  },
  {
    prop: 'suffix',
    desc: 'suffix node of input',
    type: 'React.ReactNode',
    required: 'false',
    default: '-',
  },
  {
    prop: 'className',
    type: 'string',
    required: false,
    default: '-',
  },
  {
    prop: 'style',
    type: 'React.CSSProperties',
    required: false,
    default: '-',
  },
  {
    prop: 'onChange',
    desc: 'change event of input',
    type: '(e: React.ChangeEvent<HTMLInputElement>) => void',
    required: 'false',
    default: '-',
  },
  {
    prop: 'onInput',
    desc: 'input event of input',
    type: '(e: React.FormEventHandler<HTMLInputElement>) => void',
    required: 'false',
    default: '-',
  },
  {
    prop: 'onBlur',
    desc: 'blur event of input',
    type: '(e: React.FocusEventHandler<HTMLInputElement>) => void',
    required: 'false',
    default: '-',
  },
  {
    prop: 'onFocus',
    desc: 'focus event of input',
    type: '(e: React.FocusEventHandler<HTMLInputElement>) => void',
    required: 'false',
    default: '-',
  },
];
